name = "bookuniverse"
compatibility_date = "2026-09-06"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "bookuniverse-db"
database_id = "a2ab4528-ced2-44d6-9c82-ec900a798fdd"

[[r2_buckets]]
binding = "LIBRARY"
bucket_name = "library"
